server:
  port: 9090


liwiliam:
  security:
    properties:
      validate:
        image:
          length: 6
          width: 100

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xunwu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234